apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-depl
spec:
  replicas: 1
  # selector=> how to deployment find the pods is actully crete
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    # lables that applied to the pods
    metadata:
      labels:
        app: tickets-mongo
    spec:
      containers:
        - name: tickets-mongo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
spec:
  selector:
    app: tickets-mongo
  ports:
    - name: tickets
      protocol: TCP
      port: 27017
      targetPort: 27017
